### ISSUE TITLE
Can't seems to put the device in flash mode 

### ISSUE THREAD

**Issue by the-mentor** [pio2398/W4G2#2]
I'm trying to flash the device and I'm having hard time putting it in flash mode
I also tried to put my TTL in 5v mode and connecting just the 5v and ground to the right pins so I can see the wifi ssid and check if it's up but no luck I don't see any new ssid
Any suggestions?
Thanks in advance

**Comment by pio2398** [comment]
Maybe I'm not understanding but in mode a flash mode there is no ssid.
To dump or flash new software use guide from: https://docs.libretiny.eu/docs/flashing/tools/ltchiptool/#dumping-firmware

**Comment by the-mentor** [comment]
It didn't work in flash mode or any other mode.
I ended up putting my USB TTL in v3 mode and it started working.
I don't think the module liked the v5 for some reason.

Now after I backed up the firmware I need to compile the ESPHome firmware.

Thank you very much for your help
